Add docs for UdpBatchSender
nasa/HDTN pull request #36
Opened 2023-01-05 21:42 UTC by tphnicholas

What should the `class` comment contain and what stays in the `description` section?

Are the comments descriptive enough?

2023-01-05 21:57 UTC, briantomko commented
@tphnicholas These comments in the `UdpBatchSender `look great! I suppose the description and class comments could be identical, unless there's something specific that could be added to the class comment that makes sense.

2023-01-05 22:11 UTC, tphnicholas commented
@briantomko I see, the example in `TokenRateLimiter` was more of a quick class usage showcase, was unsure if that's what you were going for. Would you like to sort this class comment out while reviewing the rest?

What do you think about documenting `@post`conditions at least for the public interface? It worked well in this case, not sure how it'll hold for more complex/involved classes, would be open to giving it a try.

2023-01-05 22:23 UTC, briantomko commented
@tphnicholas I would say class comments should be necessary if there are multiple classes in a file, but not otherwise.  Also, how were you wanting to do the pull requests (one file per pull or several/all files per pull)?  I can review the UdpBatchSender first thing in the morning.

2023-01-05 22:53 UTC, tphnicholas commented
@briantomko I was thinking grouping by sub-components for the main network components of DTN should make sense and keep the history kind of clean.

For example starting with 1 PR for the UDP layer of ltp-over-udp which would include the udp engine, ltp-over-udp induct/outduct, the delay simulation utility and this file, thoughts?

2023-01-06 12:28 UTC, briantomko commented
> @briantomko I was thinking grouping by sub-components for the main network components of DTN should make sense and keep the history kind of clean.
> 
> For example starting with 1 PR for the UDP layer of ltp-over-udp which would include the udp engine, ltp-over-udp induct/outduct, the delay simulation utility and this file, thoughts?

@tphnicholas That sounds good.  Just let me know when you feel the PR is ready for merge so I don't accidentally merge it too soon.

2023-01-06 12:52 UTC, briantomko requested changes

2023-01-06 12:52 UTC, briantomko commented on common/util/include/UdpBatchSender.h
> +     * @param underlyingCsDataToDeleteOnSentCallbackVec (internal) Vector of LtpClientServiceDataToSend::underlyingCsDataToDeleteOnSentCallback.
Should add a post condition that all three parameter vectors are moved/stolen, so after the function call, the vectors are left in an unspecified, but valid state (i.e. `vec.empty()` will return `true`)

2023-01-06 12:52 UTC, briantomko commented on common/util/include/UdpBatchSender.h
> +     * @param underlyingDataToDeleteOnSentCallbackVec (internal) Vector of LtpClientServiceDataToSend::underlyingDataToDeleteOnSentCallback.
This is the vector of raw bytes (referenced by the constBufferVecs) that must be persistent until after the OnSentPacketsCallback_t is called, and is generally used for smaller data pieces of the udp packet such as ltp headers.

2023-01-06 12:52 UTC, briantomko commented on common/util/include/UdpBatchSender.h
> +     * @param underlyingCsDataToDeleteOnSentCallbackVec (internal) Vector of LtpClientServiceDataToSend::underlyingCsDataToDeleteOnSentCallback.
This is the vector of raw bytes from the LtpClientServiceDataToSend (referenced by the constBufferVecs) that must be persistent until after the OnSentPacketsCallback_t is called, and its general use is documented here: https://github.com/nasa/HDTN/blob/master/common/ltp/src/LtpSessionSender.cpp#L268

2023-01-06 12:52 UTC, briantomko commented on common/util/include/UdpBatchSender.h
> +     * @param underlyingDataToDeleteOnSentCallbackVec (internal) Vector of LtpClientServiceDataToSend::underlyingDataToDeleteOnSentCallback.
Correct this to above comment

2023-01-06 12:52 UTC, tphnicholas commented
@briantomko You could close this one out and I incorporate this file + suggested changes over to a new PR once the rest of the files are ready for review to keep everything bundled together.

2023-01-06 13:00 UTC, briantomko commented
> @briantomko You could close this one out and I incorporate this file + suggested changes over to a new PR once the rest of the files are ready for review to keep everything bundled together.

Yes I'll close this out, and the review I did here can go to the new PR/issue.

2023-01-06 13:00 UTC, closed without merging